## num py
learn about numpy 


In [2]:
import numpy as np

In [3]:
arr1d = np.array([1,2,3,4,5,6])
print(arr1d)

[1 2 3 4 5 6]


In [4]:
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]


### list vs array

In [5]:
pylist = [1,2,3]
pyarr = np.array([1,2,3])
print(pylist*2 ,"this is list")
print(pyarr*2,"this is array")


[1, 2, 3, 1, 2, 3] this is list
[2 4 6] this is array


In [6]:
import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time : ", time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print("\n List operation time : ", time.time()-start)


 List operation time :  0.030465126037597656

 List operation time :  0.0010387897491455078


#### creating arrays from scratch


In [7]:
zeroes = np.zeros((3,4))# 3 rows 4 cols
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
full = np.full((2,2),7) #when we want to create array from other char then we use full function
print(full)

[[7 7]
 [7 7]]


In [10]:
random = np.random.random((2,3))
print(random)

[[0.44920288 0.79277516 0.85434632]
 [0.62256553 0.08813528 0.83898364]]


In [11]:
sequence = np.arange(0,10,2) #start value is 0 end value is 10-1 step value is 2
print(sequence)

[0 2 4 6 8]


### vector , matrix and tensor


In [12]:
vector =np.array([1,2,3]) #1d array is called vector
print(vector)

[1 2 3]


In [13]:
matrix = np.array([[1,2,3,4],[5,6,7,8]]) #matrix is 2d array
print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
tensor =  np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])#tensor is more than 2d array
print(tensor)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


### array property

In [15]:
print("shape is ",matrix.shape)
print("dimension is ",matrix.ndim)
print("size is how many elements ",matrix.size)
print("data type is ", matrix.dtype)


shape is  (2, 4)
dimension is  2
size is how many elements  8
data type is  int64


In [16]:
print("***note we are keep same type of data type in an array")

***note we are keep same type of data type in an array


### Array Reshaping


In [26]:
arr = np.arange(12)
print( "original array",arr)

reshaped = arr.reshape((3,4)) #this (3,4) must equals to arr.size that is 12 in this case
print("reshaped array",reshaped)


#flatten()

flattend = reshaped.flatten() #multi to single we use flatten function it ruturn the copy of array 
print(flattend)

#revel()
# ravel returns view, instead of copy

ravled = reshaped.ravel()
print(ravled)

#trasnpose -- T
transpose = reshaped.T
print(transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
