### Numpy Array Operations 


In [39]:
import numpy as np

In [40]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing ",arr[2:5])
print("with step slicing ",arr[2:5:2])
print("Negative indexing slicing",arr[-1:-5:-1])


basic slicing  [3 4 5]
with step slicing  [3 5]
Negative indexing slicing [9 8 7 6]


In [41]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Accessing elements",arr_2d[1,2])
print("Accessing  Entire rows",arr_2d[1])
print("Accessing Entire cols",arr_2d[:,1])# it mean all rown and second coloumn
print("Accessing not Entire elements",arr_2d[1:,2]) #third cols  from 2 and 3  rows


Accessing elements 6
Accessing  Entire rows [4 5 6]
Accessing Entire cols [2 5 8]
Accessing not Entire elements [6 9]


### Sorting

In [42]:
unsorted = np.array([3,7,2,4,6,5,9,1])
print("Sorted array",np.sort(unsorted))

Sorted array [1 2 3 4 5 6 7 9]


In [43]:
unsorted_2d = unsorted.reshape(4,2)
print("Unsorted 2d array\n",unsorted_2d)
print("sorted 2d array by col\n",np.sort(unsorted_2d,axis=0))
print("sorted 2d array by rows\n",np.sort(unsorted_2d,axis=1))


Unsorted 2d array
 [[3 7]
 [2 4]
 [6 5]
 [9 1]]
sorted 2d array by col
 [[2 1]
 [3 4]
 [6 5]
 [9 7]]
sorted 2d array by rows
 [[3 7]
 [2 4]
 [5 6]
 [1 9]]


### Filter

In [49]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
evenNumber = number[number%2==0]
oddNumber = number[number%2==1]
print(evenNumber)
print(oddNumber)

[ 2  4  6  8 10]
[1 3 5 7 9]


### Filter with Mask

In [ ]:
mask = number>5
print(mask)
print("number greater than 5 is :",number[mask])
'''
mask is basically expersion that store true false like it print all the value which are greater than 5 in number array
'''

[False False False False False  True  True  True  True  True]
number greater than 5 is : [ 6  7  8  9 10]


### Fancy index and np.where()

In [60]:
'''
we can create a array of indexes rather than pass only one index we can pass array as  index
'''
index = [1,5,4]
print(number[index])

''' where is just like a masking it store the index if condition is true but masking store true false value for all elements'''
result = np.where(number%2==0)
print(result)
print("NP Where :",number[result])

[2 6 5]
(array([1, 3, 5, 7, 9]),)
NP Where : [ 2  4  6  8 10]


In [ ]:
result = np.where(number>5)
result1 = np.where(number>5,number*2,number)# this line state a number which is greater than 5 that elemnt is multiply by 2 else we want same number
print(number)
print(result,result1)

[ 1  2  3  4  5  6  7  8  9 10]
(array([5, 6, 7, 8, 9]),) [ 1  2  3  4  5 12 14 16 18 20]


In [ ]:
result = np.where(number>5,number*2,number*3)
print(result)
'''
if number>5:
    number*2
else:
    number*3
'''

[ 3  6  9 12 15 12 14 16 18 20]


### Adding and removing data 

In [68]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined = arr1+arr2
print( "this add the array like matrix operation",combined)
combined = np.concatenate((arr1,arr2))
print("this merge the arr",combined)


this add the array like matrix operation [5 7 9]
this merge the arr [1 2 3 4 5 6]


In [71]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a.shape == b.shape)
a=np.array([1,2,3])
b=np.array([4,5,6,4])
print(a.shape == b.shape)

True
False


### Adding in 2d array


In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8]]) 
new_arr = np.array([9,10,11,12])
#row
with_new_row = np.vstack((matrix,new_arr))
print("original\n",matrix)
print()
print("after adding a new row\n",with_new_row)

        

original
 [[1 2 3 4]
 [5 6 7 8]]

after adding a new row
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
#cols 
new_arr = np.array([[9,10],[11,12]])
with_new_cols = np.hstack((matrix,new_arr))
print("original\n",matrix)
print()
print("after adding a new cols\n",with_new_cols)

original
 [[1 2 3 4]
 [5 6 7 8]]

after adding a new cols
 [[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]


In [ ]:
new_arr = np.array([9,10,11,12])
deleted = np.delete(new_arr,1)#delete element from 1 index
print(deleted)

[ 9 11 12]
