In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [12]:
 # Data Structure 
sales_data = np.array([
    [1,150000,180000,220000,250000],
    [2,120000,140000,160000,190000],
    [3,200000,230000,260000,300000],
    [4,180000,210000,240000,270000],
    [5,160000,185000,205000,230000]
])

print("=====Zomato sales analysis========")
print(sales_data.shape)
print("1st 3row\n",sales_data[:3])
#slicing like a [row,col] we are further slice row and col
#as we want 1st 3 row then [0:3,]

=====Zomato sales analysis========
(5, 5)
1st 3row
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [18]:
# total sales per year
print(sales_data[:,1:])
yeartotal = np.sum(sales_data[:,1:],axis=0)
particularTotal = np.sum(sales_data[:,1:],axis=1)
print(yeartotal)
print(particularTotal)


[[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
[ 810000  945000 1085000 1240000]
[800000 610000 990000 900000 780000]


In [21]:
# minimum sales per restro 
mini = np.min(sales_data[:,1:],axis=1)
print(mini)

[150000 120000 200000 180000 160000]


In [24]:
#maximum sales per year
maxi = np.max(sales_data[:,1:],axis=0)
print(maxi)

[200000 230000 260000 300000]


In [26]:
#average sales per restro
avg = np.average(sales_data[:,1:],axis=1)
print(avg)

[200000. 152500. 247500. 225000. 195000.]


In [28]:
vector1=np.array([1,2,3,4])
vector2=np.array([1,2,3,4])
print(vector1+vector2)
print(vector1*vector2)

[2 4 6 8]
[ 1  4  9 16]


In [29]:
restro = np.array(["suraj","sataym"])
vectorized_upper = np.vectorize(str.upper)
print(vectorized_upper(restro))

['SURAJ' 'SATAYM']


In [30]:
#brodcasting
monthly_sales = sales_data[:,1:]/12
print(monthly_sales)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
