### Numpy Array Operations 


In [39]:
import numpy as np

In [40]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing ",arr[2:5])
print("with step slicing ",arr[2:5:2])
print("Negative indexing slicing",arr[-1:-5:-1])


basic slicing  [3 4 5]
with step slicing  [3 5]
Negative indexing slicing [9 8 7 6]


In [41]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Accessing elements",arr_2d[1,2])
print("Accessing  Entire rows",arr_2d[1])
print("Accessing Entire cols",arr_2d[:,1])# it mean all rown and second coloumn
print("Accessing not Entire elements",arr_2d[1:,2]) #third cols  from 2 and 3  rows


Accessing elements 6
Accessing  Entire rows [4 5 6]
Accessing Entire cols [2 5 8]
Accessing not Entire elements [6 9]


### Sorting

In [42]:
unsorted = np.array([3,7,2,4,6,5,9,1])
print("Sorted array",np.sort(unsorted))

Sorted array [1 2 3 4 5 6 7 9]


In [43]:
unsorted_2d = unsorted.reshape(4,2)
print("Unsorted 2d array\n",unsorted_2d)
print("sorted 2d array by col\n",np.sort(unsorted_2d,axis=0))
print("sorted 2d array by rows\n",np.sort(unsorted_2d,axis=1))


Unsorted 2d array
 [[3 7]
 [2 4]
 [6 5]
 [9 1]]
sorted 2d array by col
 [[2 1]
 [3 4]
 [6 5]
 [9 7]]
sorted 2d array by rows
 [[3 7]
 [2 4]
 [5 6]
 [1 9]]


### Filter

In [49]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
evenNumber = number[number%2==0]
oddNumber = number[number%2==1]
print(evenNumber)
print(oddNumber)

[ 2  4  6  8 10]
[1 3 5 7 9]


### Filter with Mask

In [ ]:
mask = number>5
print(mask)
print("number greater than 5 is :",number[mask])
'''
mask is basically expersion that store true false like it print all the value which are greater than 5 in number array
'''

[False False False False False  True  True  True  True  True]
number greater than 5 is : [ 6  7  8  9 10]


### Fancy index and np.where()

In [ ]:
'''
we can create a array of indexes rather than pass only one index we can pass array as  index
'''
index = [1,5,4]
print(number[index])

''' where is just like a masking it store the index if condition is true but masking store true false value for all elements'''
result = np.where(number%2==0)
print(result)
print("NP Where :",number[result])

[2 6 5]
(array([1, 3, 5, 7, 9]),)
NP Where : [ 2  4  6  8 10]
